{
 "title": "Dashboard 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Model Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (model_version)(   increase(sms_checker_actions_total[5m]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "increase(sms_checker_actions_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per Model",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(   0.95,   rate(sms_checker_classify_latency_seconds_bucket[5m]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(sms_checker_actions_total{result=\"error\"}[5m])) / sum(increase(sms_checker_actions_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}