{
 "title": "Dashboard 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sms_checker_active_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(sms_checker_classify_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, rate(sms_checker_classify_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, rate(sms_checker_classify_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-flight request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sms_checker_in_flight_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Actions total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "increase(sms_checker_actions_total{action=\"classify\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}