---
- hosts: ctrl
  become: true

  vars:
    kubeconfig_path: /etc/kubernetes/admin.conf
    metallb_namespace: metallb-system
    metallb_ip_range: 192.168.56.90-192.168.56.99
    ingress_nginx_namespace: ingress-nginx
    ingress_nginx_ip: 192.168.56.90
    dashboard_namespace: kubernetes-dashboard
    istio_lb_ip: 192.168.56.91

  tasks:
    - name: Wait for Kubernetes API to be reachable
      ansible.builtin.command:
        cmd: kubectl get nodes
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: api_check
      retries: 20
      delay: 6
      until: api_check.rc == 0
      changed_when: false

    # step 20

    - name: Apply MetalLB CRDs and core components (disable validation for CRDs)
      ansible.builtin.command:
        cmd: >
          kubectl apply
          --validate=false
          -f /vagrant/k8s/metallb-native.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Wait for MetalLB controller pod to be Ready
      ansible.builtin.command:
        cmd: >
          kubectl wait -n metallb-system
          -l app=metallb,component=controller
          --for=condition=ready pod --timeout=120s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: metallb_wait
      retries: 5
      delay: 5
      until: metallb_wait.rc == 0

    - name: Apply MetalLB IPAddressPool
      ansible.builtin.command:
        cmd: kubectl apply -f /vagrant/k8s/metallb-ip-pool.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply MetalLB L2Advertisement
      ansible.builtin.command:
        cmd: kubectl apply -f /vagrant/k8s/metallb-l2advertisement.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


    # step 21

    - name: Add ingress-nginx Helm repository
      ansible.builtin.command:
        cmd: >
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          --force-update
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Helm repo update
      ansible.builtin.command:
        cmd: helm repo update
      environment:
            KUBECONFIG: "{{ kubeconfig_path }}"
