---
- hosts: controller
  become: true

  vars:
    kubeconfig_path: /etc/kubernetes/admin.conf
    metallb_namespace: metallb-system
    metallb_ip_range: 192.168.56.90-192.168.56.99
    ingress_nginx_namespace: ingress-nginx
    ingress_nginx_ip: 192.168.56.90
    dashboard_namespace: kubernetes-dashboard
    istio_lb_ip: 192.168.56.91

  tasks:

    # step 20

    - name: Apply MetalLB CRDs and core components
      kubernetes.core.k8s:
        state: present
        src: /vagrant/k8s/metallb-native.yaml
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Apply MetalLB IPAddressPool
      kubernetes.core.k8s:
        state: present
        src: /vagrant/k8s/metallb-ip-pool.yml
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Apply MetalLB L2Advertisement
      kubernetes.core.k8s:
        state: present
        src: /vagrant/k8s/metallb-l2advertisement.yml
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Wait for MetalLB controller to be ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: metallb-system
        label_selectors:
          - app=metallb
          - component=controller
      register: metallb_pods
      until: metallb_pods.resources | length > 0 and
             metallb_pods.resources[0].status.containerStatuses[0].ready
      retries: 20
      delay: 3

    # step 21

    - name: Add ingress-nginx Helm repository
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx

    - name: Install ingress-nginx via Helm
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: "{{ ingress_nginx_namespace }}"
        create_namespace: true
        values_files:
          - /vagrant/k8s/ingress-nginx-values.yml
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true

    # step 22

    - name: Add Kubernetes Dashboard Helm repo
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard/

    - name: Install Kubernetes Dashboard
      kubernetes.core.helm:
        name: k8s-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true
        values:
          protocolHttp: true
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Create Dashboard admin user
      kubernetes.core.k8s:
        state: present
        namespace: kubernetes-dashboard
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user

    - name: Bind admin-user to cluster-admin
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: dashboard-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kubernetes-dashboard
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io

    - name: Expose Kubernetes Dashboard through Ingress
      kubernetes.core.k8s:
        state: present
        namespace: kubernetes-dashboard
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: dashboard-ingress
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          spec:
            ingressClassName: nginx
            rules:
            - host: dashboard.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kubernetes-dashboard
                      port:
                        number: 443
