---
- hosts: ctrl
  become: true

  vars:
    kubeconfig_path: /etc/kubernetes/admin.conf
    metallb_namespace: metallb-system
    metallb_ip_range: 192.168.60.90-192.168.60.99
    ingress_nginx_namespace: ingress-nginx
    ingress_nginx_ip: 192.168.60.90
    dashboard_namespace: kubernetes-dashboard
    istio_lb_ip: 192.168.60.91

  tasks:
    - name: Wait for Kubernetes API to be reachable
      ansible.builtin.command:
        cmd: kubectl get nodes
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: api_check
      retries: 20
      delay: 6
      until: api_check.rc == 0
      changed_when: false

    # step 20

    - name: Apply MetalLB CRDs and core components (disable validation for CRDs)
      ansible.builtin.command:
        cmd: >
          kubectl apply
          --validate=false
          -f /vagrant/k8s/metallb-native.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Wait for MetalLB controller pod to be Ready
      ansible.builtin.command:
        cmd: >
          kubectl wait -n metallb-system
          -l app=metallb,component=controller
          --for=condition=ready pod --timeout=120s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: metallb_wait
      retries: 5
      delay: 5
      until: metallb_wait.rc == 0

    - name: Apply MetalLB IPAddressPool
      ansible.builtin.command:
        cmd: kubectl apply -f /vagrant/k8s/metallb-ip-pool.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply MetalLB L2Advertisement
      ansible.builtin.command:
        cmd: kubectl apply -f /vagrant/k8s/metallb-l2advertisement.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


    # step 21

    - name: Add ingress-nginx Helm repository
      ansible.builtin.command:
        cmd: >
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          --force-update
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Helm repo update
      ansible.builtin.command:
        cmd: helm repo update
      environment:
            KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Install ingress-nginx via Helm
      ansible.builtin.command:
        cmd: >
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
          --namespace {{ ingress_nginx_namespace }}
          --create-namespace
          --set controller.service.loadBalancerIP={{ ingress_nginx_ip }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Wait for ingress-nginx controller pod to be Ready
      ansible.builtin.command:
        cmd: >
          kubectl wait --namespace {{ ingress_nginx_namespace }}
          --for=condition=ready pod
          --selector=app.kubernetes.io/component=controller
          --timeout=180s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: ingress_wait
      retries: 5
      delay: 5
      until: ingress_wait.rc == 0
      changed_when: false


    # step 22

    - name: Add Kubernetes Dashboard Helm repo
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard/

    - name: Install Kubernetes Dashboard
      kubernetes.core.helm:
        name: k8s-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true
        #values:
        #  protocolHttp: true
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Apply Dashboard admin user and ClusterRoleBinding
      ansible.builtin.command:
        cmd: kubectl apply -f /vagrant/k8s/dashboard-admin.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create/Update TLS secret for Dashboard HTTPS ingress
      ansible.builtin.shell: |
        kubectl create secret tls dashboard-tls \
          --namespace kubernetes-dashboard \
          --cert=/vagrant/k8s/tls/dashboard.local.crt \
          --key=/vagrant/k8s/tls/dashboard.local.key \
          --dry-run=client -o yaml | kubectl apply -f -
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


    - name: Apply Dashboard Ingress
      ansible.builtin.command:
        cmd: kubectl apply -f /vagrant/k8s/dashboard-ingress.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    # step 23

    - name: Download Istio archive
      ansible.builtin.get_url:
        url: https://github.com/istio/istio/releases/download/1.25.2/istio-1.25.2-linux-amd64.tar.gz
        dest: /tmp/istio.tar.gz
        mode: '0644'

    - name: Extract Istio
      ansible.builtin.unarchive:
        src: /tmp/istio.tar.gz
        dest: /home/vagrant/
        remote_src: true
      become_user: vagrant

    - name: Add istioctl to PATH for vagrant user
      ansible.builtin.lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export PATH=$PATH:/home/vagrant/istio-1.25.2/bin'
        state: present
      become_user: vagrant

    - name: Install Istio with custom LoadBalancer IP
      ansible.builtin.shell: |
        /home/vagrant/istio-1.25.2/bin/istioctl install -y -f /vagrant/istio/istio-config.yml
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Enable Istio sidecar injection for default namespace
      ansible.builtin.command:
        cmd: kubectl label namespace default istio-injection=enabled --overwrite
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
