- hosts: all
  become: true

  vars:
    ssh_public_key_files: # file path relative to this playbook
      - "ssh_keys/rodrigo.pub"
      # Add more keys, we need at least 2 (2 team members)

    # STEP 7: sysctl parameters required by Kubernetes
    k8s_sysctl_settings:
      net.ipv4.ip_forward: 1
      net.bridge.bridge-nf-call-iptables: 1
      net.bridge.bridge-nf-call-ip6tables: 1

  tasks:
    # Step 4
    - name: Install team SSH keys for vagrant user
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ ssh_public_key_files }}"

    # STEP 5a
    - name: Disable swap immediately
      shell: swapoff -a
      when: ansible_facts['swaptotal_mb'] | default(0) > 0

    # STEP 5b
    - name: Ensure swap is disabled on reboot (remove swap entries from fstab)
      lineinfile:
        path: /etc/fstab
        regexp: '\sswap\s'
        state: absent
        backup: yes

    # STEP 6a
    - name: Ensure k8s kernel modules config exists
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    # STEP 6b
    - name: Ensure overlay kernel module is loaded
      modprobe:
        name: overlay
        state: present

    # STEP 6c
    - name: Ensure br_netfilter kernel module is loaded
      modprobe:
        name: br_netfilter
        state: present

    # Step 7
    - name: Ensure Kubernetes-related sysctl settings are configured
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        sysctl_set: true
        reload: true
      loop: "{{ k8s_sysctl_settings | dict2items }}"


    - name: General setup placeholder (still here for now)
      debug:
        msg: "General setup placeholder executed successfully."
