---
- hosts: node-*
  become: yes
  tasks:
    - name: Wait for control plane to be network-reachable
      wait_for:
        host: 192.168.56.100
        port: 22
        timeout: 180
        delay: 5
      
    - name: Ensure worker logic can begin
      ansible.builtin.debug:
        msg: "Worker setup placeholder executed successfully."

    # Wait for ctrl API server to be reachable
    - name: Wait for control plane API server to be reachable
      wait_for:
        host: 192.168.56.100
        port: 6443
        timeout: 300
        delay: 5
      register: api_reachable
      
    # Task 18
    - name: Generate join command on controller
      become: yes
      delegate_to: ctrl
      run_once: true
      command: kubeadm token create --print-join-command --kubeconfig=/etc/kubernetes/admin.conf
      register: join_cmd

    # Task 19
    - name: Save join command on worker
      copy:
        dest: /tmp/join-command.sh
        content: "{{ join_cmd.stdout }}\n"
        mode: '0700'

    - name: Join the Kubernetes cluster
      shell: bash /tmp/join-command.sh
      args:
        creates: /etc/kubernetes/kubelet.conf
