- hosts: all 
  become: yes
  tasks:
    - name: Wait for admin.conf to exist on controller
      delegate_to: ctrl
      run_once: true
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig_check
      retries: 30
      delay: 10
      until: kubeconfig_check.stat.exists

    - name: Wait for admin.conf to exist on controller
      delegate_to: ctrl
      run_once: true
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig_check
      retries: 30
      delay: 10
      until: kubeconfig_check.stat.exists

    - name: Generate join command on controller
      delegate_to: ctrl
      run_once: true
      command: kubeadm token create --print-join-command --kubeconfig=/etc/kubernetes/admin.conf
      register: join_cmd

    # Task 18
    - name: Generate join command on controller
      become: yes
      delegate_to: ctrl
      run_once: true
      command: kubeadm token create --print-join-command --kubeconfig=/etc/kubernetes/admin.conf
      register: join_cmd

    # Task 19
    - name: Save join command on worker
      copy:
        dest: /tmp/join-command.sh
        content: "{{ join_cmd.stdout }}\n"
        mode: '0700'

    - name: Join the Kubernetes cluster
      shell: bash /tmp/join-command.sh
      args:
        creates: /etc/kubernetes/kubelet.conf
